version: '3.8'

# Simplified docker-compose for development
# This project uses Railway's PostgreSQL database for both local and production
# No local database container needed

services:
  # You can add other services here if needed in the future
  # For example: Redis, Elasticsearch, etc.
  
# Note: To run the app locally, just use:
# npm run dev
# 
# Make sure your .env file has the Railway DATABASE_URL