[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "npm run railway:start"

[deploy.domains]
"willmclemore.com" = { }

[environments.production]
[environments.production.variables]
NODE_ENV = "production" 